server:
  port: 8888
spring:
  application:
    name: Gateway
  cloud:
    discovery:
      enabled: true
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins:
            - "http://localhost:4200"
          allowedMethods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
          allowedHeaders:
            - "*"
          allowCredentials: tru
eureka:
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
